{{- $ollamaclientDomainENV := split "," .Values.domain.ollamaclient -}}
{{- $ollamaclientDomain := index $ollamaclientDomainENV "_0" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-env
  namespace: "{{ .Release.Namespace }}"
data:
  PGID: "1000"
  PUID: "1000"
  TZ: "Etc/UTC"
  GGML_CUDA_DISABLE_GRAPHS: "1"
  OLLAMA_ORIGINS: "*"
  OLLAMA_KEEP_ALIVE: "-1"
  MODEL_NAME: "llama3.1:8b"

