# Default values for did-gate app

# Application configuration
app:
  name: did-gate
  version: '0.1.1'

# Image versions
images:
  didGate:
    repository: aboveos/did-gate
    tag: v3.4.10-rc-4
  frontend:
    repository: aboveos/did-gate-frontend
    tag: feature-did-gate-dev

# Resource configuration
resources:
  didGate:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  frontend:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

