apiVersion: v1
data:
  domain.conf: |
     {
      "_config": {
        "_blackurls": [
          "https://www.dailymail.co.uk/video/news/video-3506065/Video-Car-wash-bosses-caught-running-worldwide-people-smuggling-business.html"
        ]
      },
      "olares.com": {
        "isBlacklist": "/^https?:\/\/[^./]+\.[^./]+\.olares\.(com|cn|local)\/.*$/"
      },
      "youtubekids.com": {
        "isBlacklist": ""
      },
      "youtube.com": {
        "ytdlp": true,
        "skipUploadHtml": true,
        "skipGetHtml": true,
        "isBlacklist": "/^(https?:\/\/)?([a-zA-Z0-9-]+\.)*youtube\.com\/post(\/.*)?$/"
      },
      "bilibili.com": {
        "cookie": "required",
        "ytdlp": true,
        "skipUploadHtml": true,
        "skipGetHtml": true,
        "isBlacklist": "/^(https?:\/\/)?([a-zA-Z0-9-]+\.)*bilibili\.com\/cheese(\/.*)?$/"
      },
      "x.com": {
        "cookie": "required",
        "skipGetHtml": true,
        "isBlacklist": "/^https:\/\/(www\.)?x\.com\/i\/trending\/\d+$/,/^https:\/\/(www\.)?x\.com\/i\/events\/\d+$/"
      }
    }

kind: ConfigMap
metadata:
  name: domain-config 
  namespace: {{ .Release.Namespace }}

---
