apiVersion: v1
data:
  domain.conf: |
    # Domain configuration
    # Each domain can have the following settings:
    #   - cookie: whether cookie is required for this domain 
    #   - isBlacklist: whether blacklist is required for this domain 
    #   - uploadHtmlOnCollect: whether to upload HTML when collect (true/false), default is true
    #blackurls:
      https://www.dailymail.co.uk/video/news/video-3506065/Video-Car-wash-bosses-caught-running-worldwide-people-smuggling-business.html
    #domains:
      youtubekids.com: {'isBlacklist': ''}
      music.youtube.com: {'isBlacklist': ''}
      live.bilibili.com: {'isBlacklist': ''}
      manga.bilibili.com: {'isBlacklist': ''}
      cheese.bilibili.com: {'isBlacklist': ''}
      newsweek.com: {'isBlacklist': ''}
      usatoday.com: {'isBlacklist': ''}
      facebook.com: {'isBlacklist': ''}
      threads.com: {'isBlacklist': ''}
      instagram.com: {'isBlacklist': ''}
      pinterest.com: {'isBlacklist': ''}
      xiaohongshu.com: {'isBlacklist': ''}
      xhslink.com: {'isBlacklist': ''}
      tiktok.com: {'isBlacklist': ''}
      douyin.com: {'isBlacklist': ''}
      open.spotify.com: {'isBlacklist': ''}
      spreaker.com: {'isBlacklist': ''}
      buzzsprout.com: {'isBlacklist': ''}
      wsj.com: {'isBlacklist': ''}
      marketwatch.com: {'isBlacklist': ''}
      barrons.com: {'isBlacklist': ''}
      washingtonpost.com: {'isBlacklist': ''}
      usnews.com: {'isBlacklist': ''}
      rfi.fr: {'isBlacklist': ''}
      bloomberg.com: {'isBlacklist': ''}
      euronews.com: {'isBlacklist': ''}
      theguardian.com: {'isBlacklist': '/^https:\/\/(www\.)?theguardian\.com\/.*\/(audio|video|live)\/.*$/'}
      cnn.com: {'isBlacklist': '/^https:\/\/edition\.cnn\.com\/audio\/.*$/'}
      cnbc.com: {'isBlacklist': '/^https:\/\/(www\.)?cnbc\.com\/video(\/.*)?$/'}
      nypost.com: {'isBlacklist': '/^https:\/\/(www\.)?nypost\.com\/video(\/.*)?$/'}
      dailymail.co.uk: {'isBlacklist': '/^https:\/\/(www\.)?dailymail\.co\.uk\/video(\/.*)?$/'}
      apnews.com: {'isBlacklist': '/^https:\/\/(www\.)?apnews\.com\/live\/.*$/'}
      youtube.com: {'isBlacklist': '/^(https?:\/\/)?([a-zA-Z0-9-]+\.)*youtube\.com\/post(\/.*)?$/'}
      bilibili.com: {'cookie':'required','isBlacklist': '/^(https?:\/\/)?([a-zA-Z0-9-]+\.)*bilibili\.com\/cheese(\/.*)?$/'}
      x.com: {'cookie':'required','uploadHtmlOnCollect':false,'isBlacklist': '/^https:\/\/(www\.)?x\.com\/i\/trending\/\d+$/,/^https:\/\/(www\.)?x\.com\/i\/events\/\d+$/'}
      bbc.com: {'isBlacklist': '/^https:\/\/(www\.)?bbc\.com\/(?:.*\/)?(audio|live)\/.*$/'}
      spotify.com: {'cookie':'required'}
      reuters.com: {'isBlacklist': '','cookie':'required'}
      ft.com: {'cookie':'required'}
      vimeo.com: {'cookie':'required'}
      manybooks.net: {'cookie':'required'}
      z-library.gs: {'cookie':'required'}
      businessinsider.com: {'cookie':'required'}
      medium.com: {'cookie':'required'}

kind: ConfigMap
metadata:
  name: domain-config 
  namespace: {{ .Release.Namespace }}

---
