apiVersion: v1
data:
  domain.conf: |
    {
      "_config": {
        "_blackurls": [
          "https://example.com/blacklisted.html"
        ]
      },
      "olares.com": {
        "isBlacklist": "/^https?:\/\/[^./]+\.[^./]+\.olares\.com(\/.*)?$/"
      },
      "olares.cn": {
        "isBlacklist": "/^https?:\/\/[^./]+\.[^./]+\.olares\.cn(\/.*)?$/"
      },      
      "olares.local": {
        "isBlacklist": "/^https?:\/\/[^./]+\.[^./]+\.olares\.local(\/.*)?$/"
      },
      "youtubekids.com": {
        "isBlacklist": ""
      },
      "youtube.com": {
        "ytdlp": true,
        "skipUploadHtml": true,
        "skipGetHtml": true,
        "isBlacklist": "/^(https?:\/\/)?(music\.youtube\.com(\/.*)?|(www\.)?youtube\.com\/post(\/.*)?)$/"
      },
      "bilibili.com": {
        "cookie": "required",
        "ytdlp": true,
        "skipUploadHtml": true,
        "skipGetHtml": true,
        "isBlacklist": "/^(https?:\/\/)?((live\.|manga\.|cheese\.)bilibili\.com(\/.*)?|([a-zA-Z0-9-]+\.)*bilibili\.com\/cheese(\/.*)?)$/"
      },
      "x.com": {
        "cookie": "required",
        "skipGetHtml": true,
        "isBlacklist": "/^https:\/\/(www\.)?x\.com\/i\/trending\/\d+$/,/^https:\/\/(www\.)?x\.com\/i\/events\/\d+$/"
      },
      "pornhub.com": {
        "ytdlp": true,
        "skipUploadHtml": true,
        "skipGetHtml": true
      },
      "newsweek.com": {
        "isBlacklist": ""
      },
      "usatoday.com": {
        "isBlacklist": ""
      },
      "facebook.com": {
        "isBlacklist": ""
      },
      "threads.com": {
        "isBlacklist": ""
      },
      "instagram.com": {
        "isBlacklist": ""
      },
      "pinterest.com": {
        "isBlacklist": ""
      },
      "xiaohongshu.com": {
        "isBlacklist": ""
      },
      "xhslink.com": {
        "isBlacklist": ""
      },
      "tiktok.com": {
        "isBlacklist": ""
      },
      "douyin.com": {
        "isBlacklist": ""
      },
      "open.spotify.com": {
        "isBlacklist": ""
      },
      "spreaker.com": {
        "isBlacklist": ""
      },
      "buzzsprout.com": {
        "isBlacklist": ""
      },
      "wsj.com": {
        "isBlacklist": ""
      },
      "marketwatch.com": {
        "isBlacklist": ""
      },
      "barrons.com": {
        "isBlacklist": ""
      },
      "washingtonpost.com": {
        "isBlacklist": ""
      },
      "usnews.com": {
        "isBlacklist": ""
      },
      "rfi.fr": {
        "isBlacklist": ""
      },
      "bloomberg.com": {
        "isBlacklist": ""
      },
      "euronews.com": {
        "isBlacklist": ""
      },
      "reuters.com": {
        "isBlacklist": ""
      },
      "theguardian.com": {
        "isBlacklist": "/^https:\/\/(www\.)?theguardian\.com\/.*\/(audio|video|live)\/.*$/"
      },
      "cnn.com": {
        "isBlacklist": "/^https:\/\/edition\.cnn\.com\/audio\/.*$/"
      },
      "cnbc.com": {
        "isBlacklist": "/^https:\/\/(www\.)?cnbc\.com\/video(\/.*)?$/"
      },
      "nypost.com": {
        "isBlacklist": "/^https:\/\/(www\.)?nypost\.com\/video(\/.*)?$/"
      },
      "dailymail.co.uk": {
        "isBlacklist": "/^https:\/\/(www\.)?dailymail\.co\.uk\/video(\/.*)?$/"
      },
      "apnews.com": {
        "isBlacklist": "/^https:\/\/(www\.)?apnews\.com\/live\/.*$/"
      },
      "bbc.com": {
        "isBlacklist": "/^https:\/\/(www\.)?bbc\.com\/(?:.*\/)?(audio|live)\/.*$/"
      },
    }
kind: ConfigMap
metadata:
  name: domain-config 
  namespace: {{ .Release.Namespace }}

---
