olaresManifest.version: '0.8.1'
olaresManifest.type: app
metadata:
  name: grafana
  appid: grafana
  description: Grafana is a multi-platform open source analytics and interactive visualization web application.
  icon: https://us1.discourse-cdn.com/grafana/original/2X/c/ca5b1c3e730d294bc8b3a6a27cc178c279e97fb0.png
  version: '1.0.2'
  title: Grafana
  categories:
  - Productivity
  - Utilities
permission:
  appData: true
  appCache: true
spec:
  versionName: 0.0.24
  fullDescription: |
    Grafana is a multi-platform open source analytics and interactive visualization web application.

  developer: grafana
  website: https://grafana.com/
  sourceCode: https://github.com/grafana/grafana
  submitter: Olares
  locale:
  - en-US
  - zh-CN
  doc: https://github.com/grafana/grafana/blob/main/README.md
  license:
  - text: MIT
    url: https://github.com/grafana/grafana?tab=AGPL-3.0-1-ov-file
  requiredMemory: 512Mi
  limitedMemory: 1024Mi
  requiredDisk: 128Mi
  limitedDisk: 256Mi
  requiredCpu: 100m
  limitedCpu: 2000m
  supportArch:
  - amd64
options:
  allowedOutBoundPorts:
    - 3890
    - 80
    - 443
  dependencies:
  - name: olares
    type: system
    version: '>=1.12.3-0'
entrances:
- name: grafana
  port: 3000
  host: grafana
  title: Grafana
  icon: https://us1.discourse-cdn.com/grafana/original/2X/c/ca5b1c3e730d294bc8b3a6a27cc178c279e97fb0.png
envs:
  - envName: GF_USERNAME
    type: string
    required: true
    editable: false
  - envName: GF_PASSWORD
    type: password
    required: true
    editable: false