{{- $clickhouse_account_secret := (lookup "v1" "Secret" .Release.Namespace "clickhouse-account-info") -}}
{{- $clickhouse_password := "" -}}
{{ if $clickhouse_account_secret -}}
{{ $clickhouse_password = (index $clickhouse_account_secret "data" "password") }}
{{ else -}}
{{ $clickhouse_password = randAlphaNum 16 | b64enc }}
{{- end -}}
---
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: clickhouse
  namespace: {{ .Release.Namespace }}
spec:
  clusterDef: clickhouse
  topology: cluster
  terminationPolicy: Delete
  componentSpecs:
    - name: ch-keeper
      componentDef: clickhouse-keeper-1
      replicas: 1
      resources:
        limits:
          cpu: '0.5'
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 1Gi
      systemAccounts:
        - name: admin
          secretRef:
            name: clickhouse-account-info
            namespace: {{ .Release.Namespace }}
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
  shardings:
    - name: clickhouse
      shards: 1
      template:
        name: clickhouse  # each shard is a clickhouse component, with 2 replicas
        componentDef: clickhouse-1
        replicas: 1
        systemAccounts:
          - name: admin # name of the system account
            secretRef:
              name: clickhouse-account-info
              namespace: {{ .Release.Namespace }}
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        volumeClaimTemplates:
          - name: data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 40Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-account-info
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ $clickhouse_password }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/managed-by: kubeblocks
  name: clickhouse-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http-metrics
      port: 8001
      protocol: TCP
      targetPort: http-metrics
    - name: http
      port: 8123
      protocol: TCP
      targetPort: http
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
    - name: tcp
      port: 9000
      protocol: TCP
      targetPort: tcp
    - name: tcp-mysql
      port: 9004
      protocol: TCP
      targetPort: tcp-mysql
    - name: tcp-postgresql
      port: 9005
      protocol: TCP
      targetPort: tcp-postgresql
    - name: http-intersrv
      port: 9009
      protocol: TCP
      targetPort: http-intersrv
    - name: https-intersrv
      port: 9010
      protocol: TCP
      targetPort: https-intersrv
    - name: tcp-secure
      port: 9440
      protocol: TCP
      targetPort: tcp-secure
  selector:
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/managed-by: kubeblocks
    apps.kubeblocks.io/release-phase: stable
    apps.kubeblocks.io/sharding-name: clickhouse
  type: ClusterIP

